### ISSUE TITLE
Add RichIncrementalOperation parent class for incremental operation

### ISSUE THREAD

**Issue by 0xNacho** [proteus-h2020/proteus-backend#2]
As a wrapper class, we should include a new class called **RichIncrementalOperation** and remove the current inheritance.
From: 
```java
public class IncrementalAverage<IN> extends RichWindowFunction<IN, Tuple3<String, Double, Integer>, Tuple, GlobalWindow> {
...
}
```
To:
```java
public class IncrementalAverage<IN> extends RichIncrementalOperation<IN> {
...
}
```

Furthermore, we may need (in the future) to define some common functions for all of them.

**Comment by zequihg50** [comment]
Current usage:
`public class IncrementalAverage<IN> extends IncrementalOperation<IN, Tuple3<String, Double, Integer>> {...}`

Other operations may collect different types:
`public class IncrementalVariance<IN>
    extends IncrementalOperation<IN, Double> {...}`
