### ISSUE TITLE
Incremental operations return type

### ISSUE THREAD

**Issue by 0xNacho** [proteus-h2020/proteus-backend#3]
@zequihg50 Thanks for the fix on #2!

I think it's time to care about the output formats.

Let see the current implementation of some incOps.
Covariance:
```Java
public class IncrementalCovariance<IN> extends IncrementalOperation<IN, Double> {
...
}
```
Average:
```Java
public class IncrementalAverage<IN> extends IncrementalOperation<IN, Tuple3<String, Double, Integer>> {
...
}
```
As can be seen, these incremental operation return non-homogeneous types (IncrementalCovariance returns a **Double** while IncrementalAverage returns a **Tuple3**).

What about creating a new data type *ProteusResult* which forces all the incops to return values with this format? we could force  **OUT**  to be *ProteusResult* in the IncrementalOperation abstract class.

With this approach we may need some extended class from *ProteusResult*, or not. We will see...

A possible solution to the issue:
```Java
public class IncrementalCovariance<IN> extends IncrementalOperation<IN> {
...
}
```
Average:
```Java
public class IncrementalAverage<IN> extends IncrementalOperation<IN> {
...
}
```
Incremental Operation
```Java
public abstract class IncrementalOperation<IN> extends RichWindowFunction<IN, ProteusResult, Tuple, GlobalWindow> {
...
}
```

@zequihg50 @jorgeyp @davidpvalenzuela what are your thoughts on this?

**Comment by zequihg50** [comment]
My proposal:

Implement IncrementalAverageResult, IncrementalVarianceResult... all them should extend ProteusResult but every operator collects it's concrete result, no ProteusResut, i.e:

Incremental Operation:
`public abstract class IncrementalOperation<IN> extends RichWindowFunction<IN, ? extends ProteusResult, Tuple, GlobalWindow> {
...
}`

IncrementalAverage:
`public class IncrementalAverage<IN> extends IncrementalOperation<IN, IncrementalAverageResult> {
...
}`

IncrementalCovariance:
`public class IncrementalCovariance<IN> extends IncrementalOperation<IN, IncrementalCovarianceResult> {
...
}`

**Comment by 0xNacho** [comment]
That's what I mean by *we may need some extended class from ProteusResult* :smile:  

Thanks @zequihg50 !

**Comment by 0xNacho** [comment]
As shows [IncrementalOperation.java](https://github.com/proteus-h2020/proteus-backend/blob/development/src/main/java/com/treelogic/proteus/flink/incops/IncrementalOperation.java), all the Incremental Operation now return a IncResult POJO class.
